# before building, don`t forget to delete the cache file ~/.stack/custom-plan/yaml/

resolver: https://lts.math.bio/bcd-lts-dev.yaml

package-indices:
- name: LTS-index
  download-prefix: https://hackage.math.bio/hackage.fpcomplete.com/package/
  http: https://hackage.math.bio/hackage.fpcomplete.com/00-index.tar.gz
- name: Hackage Biocad
  download-prefix: http://hackage.biocad.ru/package/
  http: http://hackage.biocad.ru/00-index.tar.gz

# package and necessary repos that are not included in the BCD-LTS
packages:
- '.'

# necessary extra-deps that are not included in the BCD-LTS
extra-deps:
- aeson-picker-0.1.0.1

# https://github.com/commercialhaskell/stack/issues/3520
ignore-revision-mismatch: true

flags: {}

extra-package-dbs: []
